### ISSUE TITLE
Markiza.sk add on shows empty lists

### ISSUE THREAD

**Issue by ivanmulder** [kodi-czsk/plugin.video.markiza.sk#8]
Hi there,

Addon shows empty folders - no videos from archive. Either "najnovsie videa" and also "podla datumu" is empty. Addon used to work well some 2 weeks ago.

Addon Version 1.0.7
OpenElec 6.0.0

Thanks for working on this! You guys rock!

Thanks,
Marian

**Comment by mx3L** [comment]
Hello, 

You're using old version of addon, there is currently 1.1.2 version available. You have to install it manually since auto-updates are not working.
1. remove old version
2. download new version - https://github.com/kodi-czsk/plugin.video.markiza.sk/archive/master.zip
3. install it in Kodi (Install from zipfile)

Hope it helps..

**Comment by mx3L** [comment]
auto-updates are again working so no need to install manually.
